/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class term_NativeTermSize */

#ifndef _Included_term_NativeTermSize
#define _Included_term_NativeTermSize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      term_NativeTermSize
 * Method:     rawTermSize
 * Signature:  ()I
 */
JNIEXPORT jint JNICALL Java_term_NativeTermSize_rawTermSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
