name: CI
on:
  push:
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest] #, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2
      - run: sbt "set every fork := true" +test
        shell: bash
        env:
          TERM: dumb
      - run: sbt +test
        shell: bash
        env:
          TERM: dumb
