name: Release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  native-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        include:
          - os: macOS-latest
            platform: mac-x86_64
            libname: libterm-size.dylib
          - os: ubuntu-latest
            platform: linux-x86_64
            libname: libterm-size.so
          - os: windows-latest
            platform: windows-amd64
            libname: bin/term-size.dll
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2
      - run: sbt "show term-size/nativeCompile"
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: libterm-size-${{ matrix.platform }}
          path: term-size/target/native/${{ matrix.platform }}/bin/${{ matrix.libname }}

  publish:
    needs: native-artifacts
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - uses: actions/download-artifact@v2
        with:
          name: libterm-size-mac-x86_64
          path: term-size/lib_native/mac-x86_64
      - uses: actions/download-artifact@v2
        with:
          name: libterm-size-linux-x86_64
          path: term-size/lib_native/linux-x86_64
      - uses: actions/download-artifact@v2
        with:
          name: libterm-size-windows-amd64
          path: term-size/lib_native/windows-amd64
      - run: find term-size/lib_native
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
